apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-elasticpot-config
  namespace: honeypot
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /opt/elasticpot/log/elasticpot.json
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: message  # Added this line
      tail_files: true
      fields:
        event.dataset: elasticpot.honeypot
        event.module: elasticpot
      fields_under_root: true

    processors:
      - add_host_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
      - rename:
          fields:
            - from: "src_ip"
              to: "source.ip"
            - from: "dst_ip"
              to: "destination.ip"
            - from: "src_port"
              to: "source.port"
            - from: "dst_port"
              to: "destination.port"
            - from: "user_agent"
              to: "user_agent.original"
            - from: "eventid"
              to: "event.action"
            - from: "sensor"
              to: "observer.name"
      - timestamp:
          field: timestamp
          layouts:
            - '2006-01-02T15:04:05.999999999Z'
            - '2006-01-02T15:04:05Z'
          test:
            - '2025-06-02T07:59:11.730218Z'
      - drop_fields:
          fields: ["unixtime", "host"]

    setup.ilm.enabled: false
    setup.template.enabled: false

    output.elasticsearch:
      hosts: ["https://elasticsearch-master.honeypot.svc.cluster.local:9200"]
      username: "elastic"
      password: "U2sTpqA409jpGVHK"
      ssl.verification_mode: "none"
      allow_older_versions: true
      indices:
        - index: "honeypot-elasticpot-%{+yyyy.MM.dd}"

    setup.kibana:
      host: "http://kibana-kibana:5601"
      username: "elastic"
      password: "U2sTpqA409jpGVHK"

    logging.level: debug
    logging.to_files: true
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644