# redishoneypot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redishoneypot
spec:
  selector:
    app: redishoneypot
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30637  # Expose on high port number
  type: NodePort