apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /cowrie-logs/cowrie.json
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: message
      fields:
        event.dataset: cowrie.honeypot
        event.module: cowrie
      fields_under_root: true
      processors:
        - add_host_metadata: ~
        - add_cloud_metadata: ~
        - decode_json_fields:
            fields: ["message"]
            target: ""
            overwrite_keys: true
        - rename:
            fields:
              - from: "src_ip"
                to: "source.ip"
              - from: "dst_ip"
                to: "destination.ip"
              - from: "src_port"
                to: "source.port"
              - from: "dst_port"
                to: "destination.port"
              - from: "session"
                to: "event.id"
              - from: "timestamp"
                to: "@timestamp"
        - drop_fields:
            fields: ["message", "sensor", "protocol"]

    setup.ilm.enabled: false
    setup.template.enabled: false

    output.elasticsearch:
      hosts: ["https://elasticsearch-master.honeypot.svc.cluster.local:9200"]
      username: "elastic"
      password: "U2sTpqA409jpGVHK"
      ssl.verification_mode: "none"
      allow_older_versions: true
      indices:
        - index: "honeypot-cowrie-%{[agent.version]}-%{+yyyy.MM.dd}"
          when.equals:
            event.dataset: "cowrie.honeypot"

    setup.dashboards.enabled: true

    setup.kibana:
      host: "http://kibana-kibana:5601"
      username: "elastic"
      password: "U2sTpqA409jpGVHK"